"""Generate systemathic/_schema.py from schema/{kernel,contexts,operations,std}.json.

    python python/generate.py            write it
    python python/generate.py --check    exit 1 if it is out of date

The binding's vocabulary is the union of the layers, as in the TypeScript core: every Entity,
every Relationship (with the same ids, `Layer#index`), and every axiom.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAYERS = ["kernel", "contexts", "operations", "std"]
TARGET = Path(__file__).resolve().parent / "systemathic" / "_schema.py"


def generate() -> str:
    entities: list[tuple[str, str]] = []
    relationships: list[str] = []
    axioms: list[str] = []
    for layer in LAYERS:
        language = json.loads((ROOT / "schema" / f"{layer}.json").read_text(encoding="utf-8"))
        name = language["language"]
        entities += [(entity, name) for entity in language["entities"]]
        for index, relationship in enumerate(language["relationships"]):
            ends = []
            for end in relationship["ends"]:
                low, high = end["range"].split("..")
                ends.append(f"({end['name']!r}, {end['entity']!r}, {int(low)}, {None if high == 'N' else int(high)})")
            relationships.append(f"    ({name + '#' + str(index)!r}, {ends[0]}, {ends[1]}),")
        for axiom in language["axioms"]:
            axioms.append(f"    ({name!r}, {axiom['id']!r}, {axiom['about']!r}, {axiom['formula']!r}),")
    lines = [
        "# Generated by python/generate.py from schema/*.json. Do not edit.",
        '"""The Systemathic Languages, as data: Entities with their layer, Relationships as',
        "(id, end 0, end 1) with each end (name, Entity, min, max or None), and axioms as",
        '(layer, id, about, formula)."""',
        "",
        "ENTITIES = {",
        *[f"    {entity!r}: {layer!r}," for entity, layer in entities],
        "}",
        "",
        "RELATIONSHIPS = [",
        *relationships,
        "]",
        "",
        "AXIOMS = [",
        *axioms,
        "]",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    text = generate()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") if TARGET.exists() else ""
        if current != text:
            print(f"{TARGET} is out of date; run python python/generate.py")
            sys.exit(1)
        print(f"{TARGET} is up to date")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {TARGET}")
