/**
 * Generates packages/core/src/generated/schema.ts from schema/{kernel,contexts,operations,std}.json.
 *
 * A System is a model of the core Languages together, so the generated vocabulary is their
 * union: every Entity and Relationship each layer declares, and every axiom. An inclusion
 * names Entities of a lower layer, which are the same Entities, so it adds nothing to the
 * union; `python schema/check.py` is what verifies that inclusions resolve. Two unions are
 * generated: the core (Kernel, Contexts, Operations), and the core with Std on top.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const CORE = ["kernel", "contexts", "operations"] as const;
const STD = "std";

interface SchemaEnd { name: string; entity: string; range: string }
interface SchemaLanguage {
  language: string;
  entities: string[];
  relationships: { ends: SchemaEnd[] }[];
  axioms: { id: string; about: string; formula: string }[];
}

const root = new URL("../", import.meta.url);
const target = fileURLToPath(new URL("packages/core/src/generated/schema.ts", root));

interface Union {
  entities: string[];
  relationships: string[];
  axioms: string[];
}

function union(layers: readonly string[]): Union {
  const result: Union = { entities: [], relationships: [], axioms: [] };
  for (const layer of layers) {
    const language = JSON.parse(readFileSync(new URL(`schema/${layer}.json`, root), "utf8")) as SchemaLanguage;
    result.entities.push(...language.entities);
    language.relationships.forEach((relationship, index) => {
      const ends = relationship.ends.map((end) => {
        const [min, max] = end.range.split("..");
        return `{ name: ${JSON.stringify(end.name)}, entity: ${JSON.stringify(end.entity)}, min: ${Number(min)}, max: ${max === "N" ? "null" : Number(max)} }`;
      });
      result.relationships.push(`  { id: "${language.language}#${index}", ends: [${ends.join(", ")}] },`);
    });
    for (const axiom of language.axioms) {
      result.axioms.push(`  { language: ${JSON.stringify(language.language)}, id: ${JSON.stringify(axiom.id)}, about: ${JSON.stringify(axiom.about)}, formula: ${JSON.stringify(axiom.formula)} },`);
    }
  }
  return result;
}

function spec(name: string, entities: string, { relationships, axioms }: Union): string {
  return `export const ${name}: VocabularySpec = {
  entities: ${entities},
  relationships: [
${relationships.map((line) => "  " + line).join("\n")}
  ],
  axioms: [
${axioms.map((line) => "  " + line).join("\n")}
  ],
};`;
}

export function generate(): string {
  const core = union(CORE);
  const std = union([...CORE, STD]);
  const stdOnly = std.entities.slice(core.entities.length);

  return `// Generated by scripts/generate-schema.ts from schema/*.json. Do not edit.
import type { VocabularySpec } from "../kernel/vocabulary.js";

export const coreEntities = [
${core.entities.map((entity) => `  ${JSON.stringify(entity)},`).join("\n")}
] as const;

export type CoreEntity = (typeof coreEntities)[number];

${spec("coreSpec", "coreEntities", core)}

/** The Entities Std adds to the core. */
export const stdEntities = [
${stdOnly.map((entity) => `  ${JSON.stringify(entity)},`).join("\n")}
] as const;

/** The core with Std on top: the vocabulary a System is stored in. */
${spec("stdSpec", "[...coreEntities, ...stdEntities]", std)}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, generate());
  console.log(`wrote ${target}`);
}
