/**
 * Generates packages/core/src/generated/schema.ts from schema/{kernel,contexts,operations}.json.
 *
 * A System is a model of the core Languages together, so the generated vocabulary is their
 * union: every Entity and Relationship each layer declares, and every axiom. An inclusion
 * names Entities of a lower layer, which are the same Entities, so it adds nothing to the
 * union; `python schema/check.py` is what verifies that inclusions resolve.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const LAYERS = ["kernel", "contexts", "operations"] as const;

interface SchemaEnd { name: string; entity: string; range: string }
interface SchemaLanguage {
  language: string;
  entities: string[];
  relationships: { ends: SchemaEnd[] }[];
  axioms: { id: string; about: string; formula: string }[];
}

const root = new URL("../", import.meta.url);
const target = fileURLToPath(new URL("packages/core/src/generated/schema.ts", root));

export function generate(): string {
  const entities: string[] = [];
  const relationships: string[] = [];
  const axioms: string[] = [];

  for (const layer of LAYERS) {
    const language = JSON.parse(readFileSync(new URL(`schema/${layer}.json`, root), "utf8")) as SchemaLanguage;
    entities.push(...language.entities);
    language.relationships.forEach((relationship, index) => {
      const ends = relationship.ends.map((end) => {
        const [min, max] = end.range.split("..");
        return `{ name: ${JSON.stringify(end.name)}, entity: ${JSON.stringify(end.entity)}, min: ${Number(min)}, max: ${max === "N" ? "null" : Number(max)} }`;
      });
      relationships.push(`  { id: "${language.language}#${index}", ends: [${ends.join(", ")}] },`);
    });
    for (const axiom of language.axioms) {
      axioms.push(`  { language: ${JSON.stringify(language.language)}, id: ${JSON.stringify(axiom.id)}, about: ${JSON.stringify(axiom.about)}, formula: ${JSON.stringify(axiom.formula)} },`);
    }
  }

  return `// Generated by scripts/generate-schema.ts from schema/*.json. Do not edit.
import type { VocabularySpec } from "../kernel/vocabulary.js";

export const coreEntities = [
${entities.map((entity) => `  ${JSON.stringify(entity)},`).join("\n")}
] as const;

export type CoreEntity = (typeof coreEntities)[number];

export const coreSpec: VocabularySpec = {
  entities: coreEntities,
  relationships: [
${relationships.map((line) => "  " + line).join("\n")}
  ],
  axioms: [
${axioms.map((line) => "  " + line).join("\n")}
  ],
};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, generate());
  console.log(`wrote ${target}`);
}
